---
title: "Divvy Bikes"
author: "Zack Larsen"
date: "May 18, 2019"
output: 
  flexdashboard::flex_dashboard:
    social: [ "twitter", "facebook", "github", "menu" ]
    source: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard


library(pacman)
p_load(flexdashboard, leaflet, dplyr, ggvis, here, conflicted, data.table, jsonlite, kableExtra, glue, geosphere, DT, networkD3, htmltools, geojsonio)
conflict_prefer("filter", "dplyr")

here::here()

stations <- fromJSON("https://feeds.divvybikes.com/stations/stations.json")

timestamp <- stations$lastCommunicationTime
stations <- stations$stationBeanList

empties <- stations %>% 
  select(id, stationName, availableDocks, availableBikes, postalCode) %>% 
  arrange(-availableDocks) 

```


Histogram Shiny App
=========================================

Input Selectors {.sidebar}
-----------------------------------------------------------------------

Number of bikes available across all Divvy docks.

```{r}

selectInput("zip", label = "Zip (postal) code:",
            choices = c(60605,60601,60609,60649,60614,60608,60622,60606,60607,60642,60610,60611,60654,60604,60603,60616,60602,60661,60637,60657,60647,60612,60615,60618,60613,60653,60625,60640,60619,60634,60626,606012,60621,606037,60624,60623,60645,60659,60660,60641,60630,60651,60644,60636,60617,60202,60201,60208,60639)
            ,selected = 60605)

selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Column
-----------------------------------------------------------------------

### Histogram of available bikes

```{r}
renderPlot({
  subset <- empties %>% filter(postalCode == input$zip)
  hist(subset$availableBikes, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Number of bikes available", main = "Divvy")
  
  dens <- density(subset$availableBikes, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```


Station Features {.storyboard}
=========================================


### Stations By Zip Code

```{r}

renderTable({
    empties %>% 
    filter('postalCode' == input$zip)
  })

# renderDataTable({
#     DT::datatable(empties['postalCode' == input$zip, , drop = FALSE])
#   })

```


### Standalone App

```{r}

ui <- fluidPage(
  titlePanel("Basic DataTable"),

  # Create a new Row in the UI for selectInputs
  fluidRow(
    column(4,
        selectInput("zip",
                    "Zip Code:",
                    c("All",
                      unique(as.character(stations$postalCode))))
    ),
    column(4,
        selectInput("bikes",
                    "Available Bikes:",
                    c("All",
                      unique(sort(stations$availableBikes))))
    ),
    column(4,
        selectInput("docks",
                    "Available Docks:",
                    c("All",
                      unique(sort(stations$availableDocks))))
    )
  ),
  # Create a new row for the table.
  DT::dataTableOutput("table")
)



server <- function(input, output) {

  # Filter data based on selections
  output$table <- DT::renderDataTable(DT::datatable({
    data <- stations
    if (input$zip != "All") {
      data <- data[data$postalCode == input$zip,]
    }
    if (input$bikes != "All") {
      data <- data[data$availableBikes >= input$bikes,]
    }
    if (input$docks != "All") {
      data <- data[data$availableDocks == input$docks,]
    }
    data
  }))

}

shinyApp(ui, server)

```


### Standalone App (Example)

```{r}

# Load the ggplot2 package which provides
# the 'mpg' dataset.
library(ggplot2)

ui <- fluidPage(
  titlePanel("Basic DataTable"),

  # Create a new Row in the UI for selectInputs
  fluidRow(
    column(4,
        selectInput("man",
                    "Manufacturer:",
                    c("All",
                      unique(as.character(mpg$manufacturer))))
    ),
    column(4,
        selectInput("trans",
                    "Transmission:",
                    c("All",
                      unique(as.character(mpg$trans))))
    ),
    column(4,
        selectInput("cyl",
                    "Cylinders:",
                    c("All",
                      unique(as.character(mpg$cyl))))
    )
  ),
  # Create a new row for the table.
  DT::dataTableOutput("table")
)

server <- function(input, output) {

  # Filter data based on selections
  output$table <- DT::renderDataTable(DT::datatable({
    data <- mpg
    if (input$man != "All") {
      data <- data[data$manufacturer == input$man,]
    }
    if (input$cyl != "All") {
      data <- data[data$cyl == input$cyl,]
    }
    if (input$trans != "All") {
      data <- data[data$trans == input$trans,]
    }
    data
  }))

}

shinyApp(ui, server)

```


### Standalone App (Example2)

```{r}

server <- function(input, output) {

  # display 10 rows initially
  output$ex1 <- DT::renderDataTable(
    DT::datatable(iris, options = list(pageLength = 25))
  )

  # -1 means no pagination; the 2nd element contains menu labels
  output$ex2 <- DT::renderDataTable(
    DT::datatable(
      iris, options = list(
        lengthMenu = list(c(5, 15, -1), c('5', '15', 'All')),
        pageLength = 15
      )
    )
  )

  # you can also use paging = FALSE to disable pagination
  output$ex3 <- DT::renderDataTable(
    DT::datatable(iris, options = list(paging = FALSE))
  )

  # turn off filtering (no searching boxes)
  output$ex4 <- DT::renderDataTable(
    DT::datatable(iris, options = list(searching = FALSE))
  )

  # write literal JS code in JS()
  output$ex5 <- DT::renderDataTable(DT::datatable(
    iris,
    options = list(rowCallback = DT::JS(
      'function(row, data) {
        // Bold cells for those >= 5 in the first column
        if (parseFloat(data[1]) >= 5.0)
          $("td:eq(1)", row).css("font-weight", "bold");
      }'
    ))
  ))
}

ui <- 

navbarPage(
  title = 'DataTable Options',
  tabPanel('Display length',     DT::dataTableOutput('ex1')),
  tabPanel('Length menu',        DT::dataTableOutput('ex2')),
  tabPanel('No pagination',      DT::dataTableOutput('ex3')),
  tabPanel('No filtering',       DT::dataTableOutput('ex4')),
  tabPanel('Function callback',  DT::dataTableOutput('ex5'))
)


shinyApp(ui, server)



```


### Shiny Leaflet Example

```{r}

ui <- fluidPage(
  leafletOutput("mymap"),
  p(),
  actionButton("recalc", "New points")
)

server <- function(input, output, session) {

  points <- eventReactive(input$recalc, {
    cbind(rnorm(40) * 2 + 13, rnorm(40) + 48)
  }, ignoreNULL = FALSE)

  output$mymap <- renderLeaflet({
    leaflet() %>%
      addProviderTiles(providers$Stamen.TonerLite,
        options = providerTileOptions(noWrap = TRUE)
      ) %>%
      addMarkers(data = points())
  })
}

shinyApp(ui, server)

```


### Standalone Zip Map

```{r}

ui <- fluidPage(
  titlePanel("Divvy Stations By Zip Code"),
  leafletOutput("mymap"),
  p(),
  #actionButton("recalc", "New points")
  # Create a new Row in the UI for selectInputs
  fluidRow(
    column(4,
        selectInput("zip",
                    "Zip Code:",
                    c("All",
                      unique(as.character(stations$postalCode))))))
)

server <- function(input, output) {

  data <- stations
  if (input$zip != "All") {
    data <- data[data$postalCode == input$zip,]
  }
  
  output$mymap <- renderLeaflet({
  my_map <- leaflet(data) %>%
    addTiles() %>%
    addMarkers(lat = data$latitude,
               lng = data$longitude,
               popup = data$stationName,
               label = data$id)
  })
}

shinyApp(ui, server)

```


Zip Code Selector Map
=========================================

Input Selectors {.sidebar}
-----------------------------------------------------------------------

Number of bikes available across all Divvy docks.

```{r}

selectInput("zip", label = "Zip (postal) code:",
              choices = stations$postalCode %>% unique()
              ,selected = 60605)

```

Map
-----------------------------------------------------------------------

### Map of stations in selected zip code

```{r}

# renderPlot({
# 
#   data <- stations
#   if (input$zip != "All") {
#     data <- data[data$postalCode == input$zip,]
#   }
#   
#   #output$mymap <- renderLeaflet({
#   my_map <- leaflet(data) %>%
#     addTiles() %>%
#     addMarkers(lat = data$latitude,
#                lng = data$longitude,
#                popup = data$stationName,
#                label = data$id)
#   #})
#   my_map
#   
# })




renderLeaflet({
  
  data <- stations
  if (input$zip != "All") {
    data <- data[data$postalCode == input$zip,]
  }
  
  #output$mymap <- renderLeaflet({
  my_map <- leaflet(data) %>%
    addTiles() %>%
    addMarkers(lat = data$latitude,
               lng = data$longitude,
               popup = data$stationName,
               label = data$id)
  #})
  my_map
  
})


```
